-- PayPal subscription records for Knobull memberships.
-- Run this once in Supabase SQL Editor before testing the subscription flow.

create table if not exists memberships (
  user_id uuid primary key references auth.users not null,
  plan_key text not null check (
    plan_key in (
      'standard_monthly',
      'standard_yearly',
      'unlimited_monthly',
      'unlimited_yearly'
    )
  ),
  tier text not null check (tier in ('standard', 'unlimited')),
  billing_interval text not null check (billing_interval in ('month', 'year')),
  question_limit_weekly integer,
  paypal_subscription_id text not null unique,
  paypal_plan_id text,
  status text not null default 'approval_pending',
  current_period_started_at timestamptz default now(),
  downgrade_used_at timestamptz,
  downgrade_locked_until timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table memberships enable row level security;

drop policy if exists "Users read own membership" on memberships;
create policy "Users read own membership" on memberships
  for select using (auth.uid() = user_id);

revoke insert, update, delete on memberships from anon, authenticated;

create table if not exists question_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  session_id uuid references sessions(id) on delete cascade not null,
  student_message_id bigint references messages(id) on delete cascade not null unique,
  expert_id uuid references auth.users not null,
  expert_message_id bigint references messages(id) on delete cascade not null unique,
  week_start date not null,
  answered_at timestamptz default now()
);

create index if not exists idx_question_usage_user_week on question_usage(user_id, week_start);
alter table question_usage enable row level security;

drop policy if exists "Users read own question usage" on question_usage;
create policy "Users read own question usage" on question_usage
  for select using (auth.uid() = user_id);

revoke insert, update, delete on question_usage from anon, authenticated;
