-- Adds answered-question usage tracking and downgrade policy fields.
-- Run this once in Supabase SQL Editor.

alter table memberships
  add column if not exists current_period_started_at timestamptz default now(),
  add column if not exists downgrade_used_at timestamptz,
  add column if not exists downgrade_locked_until timestamptz;

update memberships
set current_period_started_at = coalesce(current_period_started_at, created_at, now())
where current_period_started_at is null;

create table if not exists question_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  session_id uuid references sessions(id) on delete cascade not null,
  student_message_id bigint references messages(id) on delete cascade not null unique,
  expert_id uuid references auth.users not null,
  expert_message_id bigint references messages(id) on delete cascade not null unique,
  week_start date not null,
  answered_at timestamptz default now()
);

create index if not exists idx_question_usage_user_week on question_usage(user_id, week_start);
create unique index if not exists idx_question_usage_expert_message_id on question_usage(expert_message_id);
alter table question_usage enable row level security;

drop policy if exists "Users read own question usage" on question_usage;
create policy "Users read own question usage" on question_usage
  for select using (auth.uid() = user_id);

revoke insert, update, delete on question_usage from anon, authenticated;
